name: Build

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      branch_name:
        type: string
        default: main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code (workflow_dispatch)
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ github.event.inputs.branch_name || github.ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'npm'

      - name: Install Node Dependencies
        run: |
          npm ci

      - name: Install spreet
        uses: baptiste0928/cargo-install@904927dbe77864e0f2281519fe9d5bd097a220b3 # v3.1.1
        with:
          crate: spreet
          git: https://github.com/flother/spreet
          commit: 014ce6445790cbc3008e17797925419fe8ecc8e1 # v0.12.0-dev

      - name: Build Artifacts
        run: |
          npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca # v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # NOTE(nicholas-ramsey): This could be problematic depending on the tag ref. I'm not sure if this would
          # actually checkout and deploy this specific branch, though.
          branch: main
          wranglerVersion: '3'
