name: Reviewdog GitHub Actionlint
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**/*.yml'
      - '.github/workflows/**/*.yaml'
  pull_request:
    paths:
      - '.github/workflows/**/*.yml'
      - '.github/workflows/**/*.yaml'

jobs:
  actionlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@12f7cb8c93ab327c99dec3a1d502c0f314978afd # v1.55.0
        with:
          level: warning
          fail_on_error: true
